[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "uncertainty_networks"
version = "0.0.1"
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
]
